### ISSUE TITLE
FIx scroll hidden in safari address bar bottom

### ISSUE THREAD

**Issue by DungGramer** [DungGramer/simple-design-system#13]
Can use `env(safe-area-inset-bottom)`

**Comment by DungGramer** [comment]
I have fixed!
Parent: 
```css
.sidebar {
  top: 2.5rem;
  bottom: 0;
}
```

child:
```css
.sidebar ul {
  position: absolute;
  bottom: 0;
  height: calc((100vh - 4.5rem) + env(safe-area-inset-bottom));
  width: 100%;
}
```

But i still lose spacing in top. I have update later!
